### ISSUE TITLE
User Story: Tasks

### ISSUE THREAD

**Issue by SoroushG-reza** [SoroushG-reza/my-plans#2]
**User Story**: As a **User**, I want to **create tasks to manage my activities**.

**Tasks**:
- [x] Create a "tasks" app in the project.
- [x] Create a Task model with fields for title and due date.
- [x] Implement fields for task creation and update timestamps.
- [x] Add an image field in the Task model for attaching images to tasks.
- [x] Configure the image upload path in the model.
- [ ] Implement ordering in the Task model to display tasks starting with the most recent.
