### ISSUE TITLE
Frontend User Story: Register/Login

### ISSUE THREAD

**Issue by SoroushG-reza** [SoroushG-reza/my-plans#5]
As a **User**, I want a **user friendly and responsive interface** to **manage my tasks**.

**Tasks**:
- [ ] Design and implement a responsive layout using React and Bootstrap.
- [ ] Create Signup page
- [ ] Create Login page
- [ ] Create Calender page as homepage, where the tasks in visible if logged in.
- [ ] Create components for task display, task creation, and task editing.
- [ ] Create Account page for managing account.
- [ ] Connect everything to the custom backend API.
- [ ] Test everything so that it functions and is shown as expected.
